export const START_LEARNING_SHUFFLED = 'START_LEARNING_SHUFFLED';
export const START_LEARNING_A_TO_B = 'START_LEARNING_A_TO_B';
export const START_LEARNING_B_TO_A = 'START_LEARNING_B_TO_A';
export const SUBMIT_ANSWER = "SUBMIT_ANSWER";
export const RESTART_STATE = "RESTART_STATE";
