export const BEGIN_FLASHCARD_LOADING_AJAX_CALL = 'BEGIN_FLASHCARD_LOADING_AJAX_CALL';
export const END_FLASHCARD_LOADING_AJAX_CALL = 'END_FLASHCARD_LOADING_AJAX_CALL';
export const FLASHCARD_LOADING_AJAX_CALL_ERROR = 'FLASHCARD_LOADING_AJAX_CALL_ERROR';

export const LOAD_FLASHCARDS = 'LOAD_FLASHCARDS';
export const CREATE_FLASHCARD_SUCCESS = 'CREATE_FLASHCARD_SUCCESS';
export const UPDATE_FLASHCARD_SUCCESS = 'UPDATE_FLASHCARD_SUCCESS';
export const DELETE_FLASHCARD_SUCCESS = 'DELETE_FLASHCARD_SUCCESS';
