export const BEGIN_FLASHCARD_SETS_LOADING_AJAX_CALL = 'BEGIN_FLASHCARD_SETS_LOADING_AJAX_CALL';
export const END_FLASHCARD_SETS_LOADING_AJAX_CALL = 'END_FLASHCARD_SETS_LOADING_AJAX_CALL';
export const FLASHCARD_SETS_LOADING_AJAX_CALL_ERROR = 'FLASHCARD_SETS_LOADING_AJAX_CALL_ERROR';

export const LOAD_FLASHCARD_SETS = 'LOAD_FLASHCARD_SETS';
export const CREATE_FLASHCARD_SET_SUCCESS = 'CREATE_FLASHCARD_SET_SUCCESS';
export const UPDATE_FLASHCARD_SET_SUCCESS = 'UPDATE_FLASHCARD_SET_SUCCESS';
export const DELETE_FLASHCARD_SET_SUCCESS = 'DELETE_FLASHCARD_SET_SUCCESS';

export const SAVE_FLASHCARD_IN_SET_SUCCESS = 'SAVE_FLASHCARD_IN_SET_SUCCESS';
export const DELETE_FLASHCARD_FROM_SET_SUCCESS = 'DELETE_FLASHCARD_FROM_SET_SUCCESS';
