export const ADD_TO_CART = 'ADD_TO_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const RECEIVE_FLASHCARDS = 'RECEIVE_FLASHCARDS';
export const LOAD_FLASHCARDS = 'LOAD_FLASHCARDS';
export const CREATE_FLASHCARD_SUCCESS = 'CREATE_FLASHCARD_SUCCESS';
export const UPDATE_FLASHCARD_SUCCESS = 'UPDATE_FLASHCARD_SUCCESS';
