export const SET_SEARCH_Q = 'SET_SEARCH_Q';
export const BEGIN_SEARCH_AJAX_CALL = 'BEGIN_LIBRARY_FLASHCARD_FOLDERS_LOADING_AJAX_CALL';
export const END_SEARCH_AJAX_CALL = 'END_LIBRARY_FLASHCARD_FOLDERS_LOADING_AJAX_CALL';
export const SEARCH_AJAX_CALL_ERROR = 'FLASHCARD_LIBRARY_FOLDERS_LOADING_AJAX_CALL_ERROR';
export const LOAD_SEARCH_RESULTS_SUCCESS = 'LOAD_SEARCH_RESULTS_SUCCESS';
